import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import styles from '../styles/Layout.module.css';

import StoreProvider from '@/hoc/ReduxProvider';
import SearchInput from '@/components/SearchInput';
import CardList from '@/components/CardList';
import ThemeProviderWithButton from '@/hoc/ThemeProviderWithButton';
import Pagination from '@/components/Pagination';
import { ThemeProvider } from '@/hoc/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  readonly children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ThemeProvider>
            <ThemeProviderWithButton>
              <div className={styles.manBox}>
                <SearchInput />
                <CardList />
                <Pagination />
              </div>

              {children}
            </ThemeProviderWithButton>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
